version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/eduardo/Workspace/docker/mariadb/data:/var/lib/mysql
      - /home/eduardo/Workspace/docker/mariadb/conf:/etc/mysql/conf.d

networks:
  default:
    external: 
      name: localhost-network
# Use root/example as user/password credentials
# https://hub.docker.com/_/mariadb
